import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="bg-white min-h-screen flex flex-col"
      >
        <Navbar />
        <Banner />
        <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-6">
            {children}
            </main>
      </body>
    </html>
    </ClerkProvider>
  );
}
